### ISSUE TITLE
升级到plus需要美国的信用卡，老铁你是咋弄的，由渠道吗？

### ISSUE THREAD

**Issue by dirkhe1051931999** [yuezk/chatgpt-mirror#1]

**Comment by yuezk** [comment]
我没有升级 plus，这个项目调用的是 gpt-3.5-turbo 的 API，普通用户就是这个速度。

**Comment by smallyunet** [comment]
双标卡也行

**Comment by terobox** [comment]
作者联系方式多少, 我赞助你两个120$账号KEY. 效果会好很多

**Comment by yuezk** [comment]
> 作者联系方式多少, 我赞助你两个120$账号KEY. 效果会好很多

多谢啦，不过我发现多帐号更好使，因为每个 API  key 的请求数不能超过 20 个每分钟
