### ISSUE TITLE
[CRASH] fetch执行报错

### ISSUE THREAD

**Issue by LOpSSH** [yuezk/chatgpt-mirror#13]
现象：
回车发送消息之后，卡死，控制台输出如下错误(使用代理和不使用代理，都是如下报错)。

操作系统：MacOS
Node版本：v19.7.0
启动方式：pnpm run start:debug

[Nest] 14838  - 2023/03/07 16:44:52     LOG [NestFactory] Starting Nest application...
[Nest] 14838  - 2023/03/07 16:44:52     LOG [InstanceLoader] ConfigHostModule dependencies initialized +7ms
[Nest] 14838  - 2023/03/07 16:44:52     LOG [InstanceLoader] ServeStaticModule dependencies initialized +0ms
[Nest] 14838  - 2023/03/07 16:44:52     LOG [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 14838  - 2023/03/07 16:44:52     LOG [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 14838  - 2023/03/07 16:44:52     LOG [RoutesResolver] AppController {/backend-api}: +3ms
[Nest] 14838  - 2023/03/07 16:44:52     LOG [RouterExplorer] Mapped {/backend-api/moderations, POST} route +0ms
[Nest] 14838  - 2023/03/07 16:44:52     LOG [RouterExplorer] Mapped {/backend-api/conversations, GET} route +1ms
[Nest] 14838  - 2023/03/07 16:44:52     LOG [RouterExplorer] Mapped {/backend-api/conversation, POST} route +0ms
[Nest] 14838  - 2023/03/07 16:44:52     LOG [RouterExplorer] Mapped {/backend-api/conversation/gen_title, POST} route +0ms
[Nest] 14838  - 2023/03/07 16:44:52     LOG [NestApplication] Nest application successfully started +2ms
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at fetchSSE (file:///Users/b1ghawk/Freedom/chatgpt-mirror/node_modules/.pnpm/chatgpt@5.0.6/node_modules/chatgpt/src/fetch-sse.ts:13:15)
^C ELIFECYCLE  Command failed.

**Comment by yuezk** [comment]
试试 `pnpm run start:dev`？

**Comment by LOpSSH** [comment]
> 

试过了，一样的情况。堆栈信息应该是不全的，不知道怎么让它输出更详细的日志。

**Comment by yuezk** [comment]
用 node 18 试试？

**Comment by LOpSSH** [comment]
> 

通过brew降级到了node18，还是这个情况。。放弃了
