### ISSUE TITLE
官方提供的demo，第二次交互会卡死

### ISSUE THREAD

**Issue by LOpSSH** [yuezk/chatgpt-mirror#16]
如图所示，第一轮交互没有问题，第二轮交互，光标就会卡死在那里，无法终止。
需要重新刷新网页才行。

![Screenshot_2023-03-08-09-09-50-65_a87fd7db6caa850b517aa6fa9d2fcd0e.jpg](https://user-images.githubusercontent.com/30652540/223593210-2deaf9ee-280b-44a4-81fd-50508b4348db.jpg)

**Comment by yuezk** [comment]
这个我复现过，有空看看

**Comment by LOpSSH** [comment]
`850-c9bd65f8d3d403b9.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'role')
    at o (850-c9bd65f8d3d403b9.js:1:15832)
    at 850-c9bd65f8d3d403b9.js:1:16370
    at Array.forEach (<anonymous>)
    at t.getConversationTurns (850-c9bd65f8d3d403b9.js:1:16288)
    at t.getTextFromLastNTurns (850-c9bd65f8d3d403b9.js:1:15971)
    at [[...chatId]]-0491aae983b125c5.js:1:72007
    at main-149b337e061b4d04.js:1:101106
    at Object.next (main-149b337e061b4d04.js:1:101211)
    at r (_app-315edc32b4917716.js:16:1497)
    at a (_app-315edc32b4917716.js:16:1694)
    at _app-315edc32b4917716.js:16:1753
    at new Promise (<anonymous>)
    at _app-315edc32b4917716.js:16:1635
    at [[...chatId]]-0491aae983b125c5.js:1:73055
    at onmessage (814-294a281e0bfddba1.js:1:7431)
    at 424-d1d3bfe6a3ca6c4a.js:1:1501
    at 424-d1d3bfe6a3ca6c4a.js:1:2127
    at n (424-d1d3bfe6a3ca6c4a.js:1:174)
    at async I (424-d1d3bfe6a3ca6c4a.js:1:1393)`

**Comment by looyeagee** [comment]
同样问题+1

**Comment by Fangnan700** [comment]
解决了，将850-c9bd65f8d3d403b9.js第537行的 t.message.author.role 强行改为 assistant ，再将第 538行删除即可。
![image](https://user-images.githubusercontent.com/114408463/223882128-cc9c0762-dba7-47b7-a7a9-296a0b102666.png)
![image](https://user-images.githubusercontent.com/114408463/223882159-badb2a55-8a5f-4343-88c0-2ad21e4508af.png)
![image](https://user-images.githubusercontent.com/114408463/223882197-6f85c18e-7677-43f0-ba2d-abce1b16c836.png)

**Comment by yuezk** [comment]
已修复

**Comment by yuezk** [comment]
解决办法是返回的消息中添加了 `author`

https://github.com/yuezk/chatgpt-mirror/blob/5f36bb27c2ed1b1e2158bcf84515091d65ca6cf3/src/chatgpt.service.ts#L84-L86
