### ISSUE TITLE
我update后，为什么历史记录的接口404

### ISSUE THREAD

**Issue by CoffinLove** [yuezk/chatgpt-mirror#17]
![image](https://user-images.githubusercontent.com/39045932/223632461-7986b635-3689-443d-b3b9-f5eba524ad4a.png)
![image](https://user-images.githubusercontent.com/39045932/223632589-a53eb96f-b26b-4d83-b082-4cebdb25ad77.png)

**Comment by CoffinLove** [comment]
优化后发现一个问题，找不到原因，输入代码就会报错，输入文字就没事，很奇怪
![image](https://user-images.githubusercontent.com/39045932/223634640-2749baa0-35b1-4236-b54a-690b291ca65a.png)

**Comment by yuezk** [comment]
重启过 nest 吗？

**Comment by CoffinLove** [comment]
项目重启过，nest？我是加了一层Nginx反向代理

**Comment by CoffinLove** [comment]
我看带上code的请求，/backend-api/conversation，被服务403，可是昨天还是很正常，真诡异，请求体直接调用api可以有返回，{"action":"next","messages":[{"id":"e2f5ec07-a0d3-43de-b930-a385fbbd6193","author":{"role":"user"},"role":"user","content":{"content_type":"text","parts":["\nimport os\nimport socket\n\n# 存储上一次的 IP 地址的文件路径\nIP_PATH = \"/data/scripts/ip.txt\"\n\n# 获取当前 IP 地址\ndef get_current_ip():\n    try:\n        return socket.gethostbyname('cloud.chenyuqi.vip')\n    except socket.gaierror:\n        print('Failed to resolve hostname.')\n        return None\n\n# 重启 Nginx 服务\ndef restart_nginx():\n    os.system('sudo systemctl restart nginx')"]}}],"parent_message_id":"chatcmpl-6rhZy57xv2y6ZA5JkH24WJyteTgeR","model":"text-davinci-002-render"}，头大

**Comment by yuezk** [comment]
没太明白，如果不用 nginx 做代理，直接跑能用吗？

**Comment by CoffinLove** [comment]
直接跑可以的，带code的内容可以发的，但是历史记录还是没有的，你那边都正常？

**Comment by yuezk** [comment]
历史记录的功能还没实现，其他都正常

**Comment by CoffinLove** [comment]
对的，除了历史功能，我找到原因了，因为是参数里面是大量的code，被我waf杀掉了，关闭这个站点的防火前就好

**Comment by whn3500079813** [comment]
![image](https://user-images.githubusercontent.com/94180745/224884525-4512fefe-da65-4b6a-8856-53032afe6c22.png)
请问这个搭建的时候显示404是什么问题
