### ISSUE TITLE
ChatGPT配置能否新增字段？

### ISSUE THREAD

**Issue by EricYrj** [yuezk/chatgpt-mirror#21]
您好，请问一下，ChatGPT配置能否新增以下字段：

bot_desc：AI特征，非常重要，功能等同给与AI一个身份设定
max_tokens: GPT响应字符数，最大2048，默认值512。
model: GPT选用模型，默认text-davinci-003

**Comment by yuezk** [comment]
可以

**Comment by EricYrj** [comment]
> 
非常感谢，麻烦您在README.md上编写一下配置步骤。

**Comment by yuezk** [comment]
好的，支持了之后更新一下

**Comment by yuezk** [comment]
@EricYrj 已更新
