### ISSUE TITLE
作者大大你好，一个比较严重的问题，消息间接性持续空白

### ISSUE THREAD

**Issue by kuangxiaoye** [yuezk/chatgpt-mirror#25]
我填了自己的apikey之后就会出现这种情况···在浏览器key之后依然会这样····

这是在您提供的fastapp体验网址的截图···

![image](https://user-images.githubusercontent.com/43713316/224263144-389f6564-d1eb-4872-a09a-ed1c1144015e.png)

请问这是什么问题呀

**Comment by yuezk** [comment]
错误处理的不够好，周末会修复一下

**Comment by yuezk** [comment]
已修复：https://github.com/yuezk/chatgpt-mirror#error-messages
