### ISSUE TITLE
 部署后Error sending message，Error: ChatGPT error 400

### ISSUE THREAD

**Issue by chinasoso** [yuezk/chatgpt-mirror#26]
已加反向代理，Api端口可以正常访问（下图）。
![19841678443770_ pic](https://user-images.githubusercontent.com/37648847/224291504-253f7229-0782-4b56-8303-af85dab55c53.jpg)

但提交问答时，报错，如下：
Error sending message
Error: ChatGPT error 400:

![19851678443943_ pic](https://user-images.githubusercontent.com/37648847/224292227-c0a64e57-3825-47a2-a9f2-b576331b7510.jpg)

请指导如何解决！

**Comment by yuezk** [comment]
没太明白这个网络架构是什么样的

**Comment by chinasoso** [comment]
conversation_id这个参数未获取到。

![19961678527693_ pic](https://user-images.githubusercontent.com/37648847/224477073-8a0680ff-123e-460a-ab0f-05349430916d.jpg)

**Comment by yuezk** [comment]
代理不是这样配置的，我说的代理就是一个单独代理服务器，能翻墙的哪种
