### ISSUE TITLE
问一个简单的问题，如何开机自启动pnpm?

### ISSUE THREAD

**Issue by mugua** [yuezk/chatgpt-mirror#27]
问一个简单的问题，如何开机自启动pnpm?
我每次退出ssh后，网站就打不开了，麻烦告知一下，谢谢。

**Comment by wo2429** [comment]
这还问作者，你用pm2管理器就行

**Comment by mugua** [comment]
另外，我配置好了 key , 提问后，一直出不来答案。
是不是哪里配置错了？

**Comment by wo2429** [comment]
服务器网络可以访问openai的api嘛，排查一下

**Comment by mugua** [comment]
> 服务器网络可以访问openai的api嘛，排查一下

套了CF呀！

**Comment by yuezk** [comment]
docker 或者 pm2，我用的后者

**Comment by yuezk** [comment]
> 

哪里的机器套的 CF，本地机器套 CF 可能不行，你在浏览器中访问一下 openai 的 API 看看能打开不

**Comment by mugua** [comment]
> 这还问作者，你用pm2管理器就行

谢谢，搞定了。

**Comment by mugua** [comment]
> > 
> 
> 
> 
> 哪里的机器套的 CF，本地机器套 CF 可能不行，你在浏览器中访问一下 openai 的 API 看看能打开不

用的Google Cloud Taiwan的服务器。
有可能是我的.env没配置好。

**Comment by mugua** [comment]
> > 
> 
> 
> 
> 哪里的机器套的 CF，本地机器套 CF 可能不行，你在浏览器中访问一下 openai 的 API 看看能打开不

.env这个文件除了要填api key以外，后面的HTTP_PROXY=这里需要填啥吗？我填了http://127.0.0.1:3000。
另外api key要用""括起来吗？

**Comment by mugua** [comment]
> > > 
> > 
> > 
> > 哪里的机器套的 CF，本地机器套 CF 可能不行，你在浏览器中访问一下 openai 的 API 看看能打开不
> 
> .env这个文件除了要填api key以外，后面的HTTP_PROXY=这里需要填啥吗？我填了[http://127.0.0.1:3000。](http://127.0.0.1:3000%E3%80%82) 另外api key要用""括起来吗？

第一行加了“”括起来，第三行前加了#注释掉就好了。

谢谢作者。
