### ISSUE TITLE
你好···git上传的代码和demo版本差距好大··

### ISSUE THREAD

**Issue by kuangxiaoye** [yuezk/chatgpt-mirror#29]
大佬 求更新啊···看到demo报错都有了 但是自己pull您的代码啥都没有···

是故意这样的么··

**Comment by yuezk** [comment]
确实是这样，demo 版本是基于开源的版本开发的，又加了一些定制化的功能，所以并不通用。我也会陆续地往开源的这个版本上合并一些通用的逻辑，错误处理会加进来，前端页面的一些功能的也会迁移过来，但我无法保证两个版本完全相同。

**Comment by kuangxiaoye** [comment]
没关系  我还以为是我pull的问题 能理解  能上传这些给我们学习就很好了！
