### ISSUE TITLE
How does it run behind a proxy?

### ISSUE THREAD

**Issue by smallyunet** [yuezk/chatgpt-mirror#3]
I occurred the error:

<img width="749" alt="Screenshot 2023-03-06 at 11 56 40" src="https://user-images.githubusercontent.com/20765689/223016378-970e4385-51d8-4098-94d1-b073b9435129.png">

The panic log:

<img width="803" alt="Screenshot 2023-03-06 at 11 56 52" src="https://user-images.githubusercontent.com/20765689/223016383-784c4040-1a45-4c8d-93a5-2842cb3c6fc5.png">

**Comment by yuezk** [comment]
You are blocked, the OpenAI API is blocked from China.

**Comment by smallyunet** [comment]
How can I use this?
https://github.com/transitive-bullshit/chatgpt-api/tree/v3.3.0#using-proxies

**Comment by yuezk** [comment]
I think you are looking for this. https://github.com/transitive-bullshit/chatgpt-api/issues/419, there is a solution under in the discussion.

And you can modify the code to pass the proxy. https://github.com/yuezk/chatgpt-mirror/blob/c50598309f2b55a1164932389d3a8d5cb48c4eaa/src/chatgpt.service.ts#L13

**Comment by yuezk** [comment]
You can add the `HTTP_RPOXY` environment variable to use the proxy. e.g., `HTTP_PROXY=http://127.0.0.1:1087`
