### ISSUE TITLE
plus订阅的key不能用，能不能调整一下

### ISSUE THREAD

**Issue by wo2429** [yuezk/chatgpt-mirror#40]
plus订阅的key不能用，能不能调整一下

**Comment by yuezk** [comment]
报的什么错？

**Comment by wo2429** [comment]
ChatGPT error 429: {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
