### ISSUE TITLE
model 不是 gpt-3.5-turbo-0301

### ISSUE THREAD

**Issue by yaolinhong** [yuezk/chatgpt-mirror#8]
配置了模型，但接口请求模型似乎不是gpt-3.5-turbo-0301
![image](https://user-images.githubusercontent.com/26712987/223134501-f93228fa-fa35-4139-a325-12eb23ffb409.png)

![image](https://user-images.githubusercontent.com/26712987/223134619-6dd31707-1c7c-47f1-8f38-c3cf5e7f3efc.png)

**Comment by yuezk** [comment]
`moderations` 的请求没有实际作用的，后端会直接返回成功。
https://github.com/yuezk/chatgpt-mirror/blob/b78724aac81baadb5ccc10402cd6db8b752ab7de/src/app.controller.ts#L11-L18

**Comment by yaolinhong** [comment]
嗯嗯 明白 conversation 这个接口 model也是"text-davinci-002-render"

![image](https://user-images.githubusercontent.com/26712987/223135873-3cd8bf08-56a3-4b80-a983-6546a7b6ef4e.png)

**Comment by yaolinhong** [comment]
检查了https://fastgpt.app/
也是相同的情况

![image](https://user-images.githubusercontent.com/26712987/223140266-cb4177bb-f235-4a66-87c6-35365d663600.png)
把chatGPTAPI升级至5.0.7（目前的lastest）
![image](https://user-images.githubusercontent.com/26712987/223140559-8e23ddbc-d222-4e2b-90c6-bc16954e79a5.png)
设置模型 均无法使conversation接口的model入参按照预期显示 gpt-3.5-turbo-0301

换成官网的api是否能解决这个问题 我去尝试下
https://platform.openai.com/docs/guides/chat/introduction

**Comment by yuezk** [comment]
前端只是保存的官网的静态页面而已，并没有作太多修改，也没有办法改。这个项目偷梁换柱把接口给反代了，所以并不关心前端传的模型参数，后端接口默认使用 gpt-3.5-turbo 的模型

**Comment by yaolinhong** [comment]
噢噢 明白了
